# Generated by Django 5.2.11 on 2026-02-09 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(help_text='Размер в байтах')),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'В ожидании'), ('Processing', 'В процессе'), ('Completed', 'Завершено'), ('Error', 'Ошибка')], default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ('-created_at',),
            },
        ),
    ]
