# Generated by Django 5.2.11 on 2026-02-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='files',
        ),
    ]
