# Generated by Django 5.2.11 on 2026-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_file_document_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
