# Generated by Django 5.2.11 on 2026-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/converted/'),
        ),
        migrations.AddField(
            model_name='document',
            name='internal_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/internal/'),
        ),
        migrations.AddField(
            model_name='document',
            name='target_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'XLSX')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
