# Generated by Django 5.2.11 on 2026-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_converted_file_document_internal_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='target_format',
            field=models.CharField(choices=[('PDF', 'pdf'), ('CSV', 'csv'), ('XLSX', 'xlsx')],
                                   default='PDF', max_length=10),
        ),
    ]
