# Generated by Django 5.2.11 on 2026-02-13 10:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_target_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
