# Generated by Django 5.2.11 on 2026-02-13 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='converted_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='internal_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='result_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='target_format',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='document',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='batch_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'В ожидании'), ('Processing', 'В процессе'), ('Completed', 'Завершено'), ('Error', 'Ошибка')], max_length=20),
        ),
    ]
