# Generated by Django 5.2.11 on 2026-02-16 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_document_converted_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='document',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='parsed_data',
        ),
        migrations.RemoveField(
            model_name='document',
            name='started_at',
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='batch_id',
            field=models.UUIDField(db_index=True, help_text='Общий UUID для пачки файлов, загруженных одним запросом.', verbose_name='ID группы загрузки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'На модерации'), ('Approved', 'Подтверждён'), ('Rejected', 'Отклонён')], db_index=True, max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['batch_id'], name='documents_d_batch_i_4d0c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
