# Generated by Django 5.2.11 on 2026-02-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_options_remove_document_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mime тип'),
        ),
    ]
